Jojo-Schmitz/MuseScore

- CMakeLists.txt
- libmscore/key.cpp
- libmscore/key.h
- libmscore/sig.cpp
- libmscore/sig.h
- mscore/macos/cocoabridge.h
- mscore/macos/cocoabridge.mm
- mscore/musescore.cpp
- thirdparty/rtf2html/fmt_opts.h
Resolves: https://musescore.org/en/node/19387
Resolves: https://musescore.org/en/node/323432
- **Register recent files with macOS**
- **Add hint to Open Recent menu when there are no recent files**
> [MU3.7] Show recent files in Dock icon menu on macOS

- importexport/bww/lexer.cpp
> Add some piobraich-embellishments to bww-Import

- libmscore/harmony.cpp
- libmscore/textlinebase.cpp
> Fix GH#98: Crescendo lines overlap + Chord text frame

- libmscore/layout.cpp
Backport of #17259
Resolves: #17149
> Fix bug with custom time sig at start of MMRest

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testNegativeOctave.mscx
- mtest/musicxml/io/testNegativeOctave_ref.xml
- mtest/musicxml/io/testStringData.xml
- mtest/musicxml/io/tst_mxml_io.cpp
Backport of #17490
* Fix #17185
* Fix MusicXML corruption on tuning to negative octave
> Fix GH#17185: MusicXML ignores custom string data

- .github/workflows/ci_macos.yml
- Makefile.osx
- mscore/CMakeLists.txt
and will be removed on 31-Mar-2023.
Along with that XCode 10.3 will not be available anymore either.
Resolves: #111
> macOS 10.15 is deprecated on GitHub CI

- libmscore/transpose.cpp
> Fix GH#17530: Transposition fix

- libmscore/style.cpp
> Some backwards compatibility

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlnotepitch.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/musicxmlsupport.cpp
- importexport/musicxml/musicxmlsupport.h
Backport of #17489 (so far only the import)
Resolves: #15903
> Fix GH#15903: Added MusicXML support for some accidentals

- mscore/musescore.cpp
Resolves: #143 
Real stupid typo or rather copy/paste fail.
> Fix GH#143: Some Command-line Arguments do not work in version 3.7

- libmscore/cmd.cpp
- libmscore/score.h
- mscore/shortcut.cpp
> Proposed fix #297458: implement "apply input state" command

- libmscore/scorefile.cpp
Assumption is that in a Mu4 mscz file the 1st mscx file is the real `rootfile`, the actual main score. In Mu3 and earlier it is the only `rootfile`, so this save there too.
In Mu4 pictures files are recorded as `rootfile`s too, so we read them in as such here, it there are any.
Except for `score_style.mss` and `viewsettings.json` (which both don't exist prior to Mu4 and are now read in if they are in the mscz), none of the other `rootfiles` are needed or usefull, as these represent the thumbnails (not read in Mu3 either), `soundsettings.json` (don't apply to Mu3) and the excerpts and their styles in Mu4.
> Allow Mu3 to open Mu4 mscz files

- libmscore/articulation.cpp
- libmscore/articulation.h
- vtest/cross-staff-accents.mscx
- vtest/gen
- vtest/gen.bat
> Fix GH#19139: Use correct staff for accent layout

- libmscore/tie.cpp
> Fix GH#169: Chord with tied-into grace notes is screwy

- libmscore/line.cpp
> Lines loose their line style on Mu4 import

- libmscore/chordrest.cpp
> Fix GH#177: Ornaments get lost on Mu4 import

- libmscore/pedal.cpp
> Add missing "Set to style" to Pedal Inspector

- libmscore/scorefile.cpp
- libmscore/style.cpp
- libmscore/style.h
> Fix line style settings for 3.x scores

- libmscore/scorefile.cpp
> Fix GH#165; Mu3 opens Mu4 mscz files with wrong scaled element distances

- libmscore/measure.cpp
> Fix GH#174: Staff Texts Style Expression - Import from MS4 failed

- libmscore/fermata.cpp
- libmscore/rest.cpp
- libmscore/rest.h
- vtest/fermata-1.mscx
- vtest/gen
- vtest/gen.bat
Backport of #19552
Plus another apparently forgotten change
Resolves: #19489
> Fix GH#19489: Center fermatas over rests on resized staves

- .github/workflows/ci_linux.yml
- .github/workflows/ci_lupdate.yml
- .github/workflows/ci_macos.yml
- .github/workflows/ci_tx2s3.yml
- .github/workflows/ci_vtests.yml
- .github/workflows/ci_windows.yml
> Update checkout action

- mscore/editstaff.cpp
Backport of #19566
Resolves: #19483
> Fix GH#19483: Correct staff for editing instrument after instrumentChange

- libmscore/glissando.cpp
> Draw glisses with flat caps

- libmscore/edit.cpp
- libmscore/measure.cpp
- libmscore/property.cpp
Backport of #19492
Resolves: #19092
> Fix GH#19092: Correct full measure rest in parts

- libmscore/joinMeasure.cpp
Resolves: #19323
If joining measures containing time signatures, resulting measure should have nominal time signature of preceding measure and following measure should have time signature which was the last one in joined measures (unless it has time signature already)
Backport of #19546
> Fix GH#19323: Move or remove TimeSigs of joined measures

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass1.cpp
- importexport/musicxml/importmxmlpass1.h
- mtest/musicxml/io/testLayout.xml
- mtest/musicxml/io/testSystemDistance_ref.xml
- mtest/musicxml/io/testSystemDividers.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> MusicXML: system dividers and line thickness import/export

- libmscore/element.h
- libmscore/iname.cpp
- libmscore/iname.h
- vtest/gen
- vtest/gen.bat
- vtest/instrument-names-1.mscx
Resolves: #17891
Backport of #19161
> Fix GH#17891: Instrument names follow largest stave spatium in part

- fonttools/smufl2sym-in-trans.json
- importexport/capella/capella.cpp
- importexport/guitarpro/importgtp-gp6.cpp
- importexport/musicxml/importmxmlpass2.cpp
- libmscore/clef.cpp
- libmscore/clef.h
- libmscore/sym.cpp
- mscore/menus.cpp
Resolves: #19843 
Backport of #19844
> Fix GH#19843: Implement tenor clef ottava bassa

- libmscore/barline.cpp
- libmscore/measure.cpp
- libmscore/measure.h
Resolves: #19684
Not sure the bug applies to Mu3 though, for sure not with the steps described there, as Mu3 doesn't allow to insert measures after a selection, but it doesn't seem to harm either and seems the prerequisite for the next fixes
Backport of #19743
Resolves: #19778
Resolves: #19782
Backport of #19783
> Fix GH#19684, GH#19778, GH#19782

- libmscore/style.cpp
> More Mu4 linestyle compatibility

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testInvisibleElements.xml
> Add import/export of invisible clefs to MusicXML

- libmscore/tuplet.cpp
> Use MiterJoin for drawing tuplet brackets

- libmscore/element.cpp
- libmscore/figuredbass.cpp
- libmscore/glissando.cpp
- libmscore/layoutbreak.cpp
- libmscore/lyrics.cpp
- libmscore/lyricsline.cpp
- libmscore/marker.cpp
- libmscore/measurebase.cpp
- libmscore/slurtie.cpp
- libmscore/spanner.cpp
- libmscore/spanner.h
- libmscore/tie.cpp
- libmscore/trill.cpp
- libmscore/vibrato.cpp
Backport of  #20141
Resolves: #20003
> OPTIMIZATION: Remove unnecessary calls to triggerLayoutAll

- libmscore/edit.cpp
- libmscore/figuredbass.cpp
Backport of #20139
Resolves: #17625
Had come up quite a while ago in https://musescore.org/en/node/332146
> Fix GH#17625: Link figured bass between parts & score

- libmscore/score.cpp
- mscore/selectdialog.cpp
Backport of #20137, part 2, see https://github.com/musescore/MuseScore/pull/20137#issuecomment-1823758432
> Fix "Same measure" for text lines

- libmscore/read114.cpp
- libmscore/read206.cpp
Backport of #20230, as far as it makes sense.
> Fix corruption issues on old files

- libmscore/score.cpp
- libmscore/select.h
- mscore/selectdialog.cpp
> Code cleanup

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlnotepitch.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- libmscore/figuredbass.cpp
- mtest/musicxml/io/testArpGliss3.xml
- mtest/musicxml/io/testBarStyles4.xml
- mtest/musicxml/io/testColorExport.mscx
- mtest/musicxml/io/testColorExport_ref.xml
- mtest/musicxml/io/testColors.xml
- mtest/musicxml/io/testCueNotes2_ref.xml
- mtest/musicxml/io/testLyricExtensions.xml
- mtest/musicxml/io/testLyricExtensions_ref.mscx
- mtest/musicxml/io/testMaxNumberLevel_ref.xml
- mtest/musicxml/io/testMultipleNotations_ref.xml
- mtest/musicxml/io/testNoteAttributes1.xml
- mtest/musicxml/io/testSlurTieDirection.xml
- mtest/musicxml/io/testSlurTieLineStyle.xml
- mtest/musicxml/io/testSlurs2.xml
- mtest/musicxml/io/testTrackHandling.xml
- mtest/musicxml/io/testTuplets8_ref.xml
- mtest/musicxml/io/tst_mxml_io.cpp
Backport of #19132 (plus another small change for articulations placement above/below, taken from master) 
Also fixes #17841 (for 3.x)
> Extend MusicXML color support

- importexport/musicxml/importmxmlnoteduration.cpp
- importexport/musicxml/importmxmlpass1.cpp
- importexport/musicxml/importmxmlpass1.h
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testDivsDefinedTooLate1_ref.xml
- mtest/musicxml/io/testDivsDefinedTooLate2_ref.xml
- mtest/musicxml/io/testDurationLargeError_ref.mscx
Backport of #20280
Resolves: #20273
> Fix GH#20273: Fix musicXML whole rest import

- importexport/musicxml/exportxml.cpp
- mtest/musicxml/io/testColorExport_ref.xml
Backport of #20225
Resolves: #18158
> Fix GH#18158: Do not export invisible text lines

- libmscore/duration.cpp
- libmscore/duration.h
- libmscore/paste.cpp
- mtest/libmscore/copypaste/copypaste27-ref.mscx
- mtest/libmscore/copypaste/copypaste27.mscx
- mtest/libmscore/copypaste/tst_copypaste.cpp
> Fix GH#18940: Prevent local time signature paste crash

- libmscore/read302.cpp
> Fix GH#252: Read Mu4.2+ scores too

- libmscore/clef.h
- mscore/selectdialog.cpp
Backport of #20753
Resolves: #20093
> Fix #20093: Add 'Same Subtype' selection parameter for clefs

- libmscore/scoreElement.cpp
- libmscore/types.h
- mtest/scripting/p1.log.ref
Backport of #20756
Resolves: #20291
> Fix #20291: Render flags behind noteheads

- libmscore/layout.cpp
- vtest/staffEmptiness.mscx
Backport of #20846
Resolves: #20782
> Fix GH#20782: Fix hidden staff conditions with spanners

- libmscore/layout.cpp
Backport of #21039
Resolves: #21020
> Fix GH#21020: Check hook is valid before getting width

- libmscore/glissando.cpp
Backport of #20902
Resolves: #20894
> Fix GH#20894: Cross-staff, cross-system gliss layout correction

- libmscore/note.cpp
- libmscore/note.h
Backport of #21034, just to prevent possible futur merge conflicts
> Rename relLine to absLine

- libmscore/layout.cpp
- libmscore/layoutbreak.cpp
- libmscore/layoutbreak.h
> Fix GH#280: First system indentation property of section break gets ignored

- libmscore/select.cpp
- libmscore/select.h
Backport of #21032
Resolves: #18187
> Fix GH#18187: Ensure tuplets are included in range selections

- libmscore/cmd.cpp
Backport of #20980
Resolves: #20720
> Fix GH#20720: Retain selection after addInterval

- libmscore/cmd.cpp
Backport of #21343
Resolves: #21292
Resolves: #21342
> Fix GH#21292, GH21342: Correctly explode grace notes and fix selection after exploding

- importexport/musicxml/importmxmlpass2.cpp
> Only set line to below/above if explicitly so in MusicXML

- importexport/musicxml/importmxmlpass2.cpp
> Use correct track for melisma length on XML import

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass1.cpp
Backport of #21075
Resolves: #21013
> Fix GH#21013: MusicXML: export scores in concert pitch

- importexport/musicxml/importmxmlpass2.cpp
Backport of #21400, part 4, simplified
> [MusicXML] Fix read measure numbers

- libmscore/chordrest.cpp
Backport of #21418
Resolves: #21336
> Fix GH#21336: Disappearing grace note slurs in parts on copy/paste

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testHarmony8.xml
- mtest/musicxml/io/tst_mxml_io.cpp
Backport of #21362
Resolves: #20873
> Fix GH#20873: export hidden chord symbols

- importexport/musicxml/exportxml.cpp
- mtest/musicxml/io/testColorExport.mscx
- mtest/musicxml/io/testColorExport_ref.xml
Backport of #21433
* export stem color
* export dor color and positioning
* export beam color
> MusicXML: export more color details

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importxmlfirstpass.cpp
- importexport/musicxml/musicxmlsupport.cpp
> Speed up returning empty string

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlnoteduration.cpp
- importexport/musicxml/importmxmlpass1.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- importexport/musicxml/importxml.cpp
- importexport/musicxml/importxmlfirstpass.h
- importexport/musicxml/musicxmlfonthandler.cpp
- importexport/musicxml/musicxmlsupport.cpp
- importexport/musicxml/musicxmlsupport.h
Backport of #21474 (and some more)
> Some more small adjustments for empty strings

- mscore/editstyle.cpp
- mscore/editstyle.ui
Backport of #21506, part 1 and 3, not sure I want part 2, as that'd require updated translations.
> Style dialog tweaks

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testBackupRoundingError_ref.mscx
> Set fermata direction if none is specified

- libmscore/cmd.cpp
Backport of #21436
Resolves: #21435
> Fix GH#21435: Correct cmdAddInterval selection for tied chords

- libmscore/edit.cpp
- libmscore/score.cpp
- libmscore/score.h
Backport of #20984
Resolves: #20962
Resolves: #13469
> Fix GH#20962: Keep selection when deleting, changing note/rest lengths

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testLyricColor.xml
> [MusicXML] import/export invisible lyrics

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testLyricPos.xml
- mtest/musicxml/io/testLyricPos_ref.mscx
- mtest/musicxml/io/tst_mxml_io.cpp
> [MusicXML] Read and write placement information for lyrics

- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testElision.xml
- mtest/musicxml/io/testElision_ref.mscx
- mtest/musicxml/io/tst_mxml_io.cpp
> Read lyric elision tags in MusicXML files

- libmscore/note.cpp
Backport of #21350
Resolves: #16299
> Fix GH#16299: Never keep accidentals when dragging notes

- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testLyricExtension2.xml
- mtest/musicxml/io/testLyricExtension2_ref.mscx
- mtest/musicxml/io/tst_mxml_io.cpp
> Allow multiple lyric melismas when placement is different

- importexport/musicxml/exportxml.cpp
- mtest/musicxml/io/testNotesRests2.xml
> [MusicXML] export beams starting or ending on rests

- libmscore/harmony.cpp
> Fix GH#344: Modifying an element makes a chord symbol move

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testPlacementDefaults.xml
- mtest/musicxml/io/testPlacementDefaults_ref.mscx
> Set hairpin's default placement to 'Above' on vocal stave

- libmscore/layout.cpp
Backport of #21768
Resolves: #21767
> Fix GH#21767: Don't align invisible voltas

- libmscore/layout.cpp
> Remove gaps for float mode during system layout

- share/instruments/instruments.xml
(Partial) Backport of #21810
(Sort of) Resolves: [#21670](https://www.github.com/musescore/MuseScore/issues/21670)
> Fix trombone ranges

- importexport/musicxml/importmxmlpass1.cpp
> Apply default font to all elements only when XML import config option is set

- importexport/musicxml/importmxmlpass2.cpp
> Set spanner position by checking totalY

- libmscore/tuplet.cpp
> Fix (potential) crash on null tuplet

- libmscore/rendermidi.cpp
> Fix possible undefined behaviour in MIDI

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testCueNotes3_ref.mscx
- mtest/musicxml/io/testElision_ref.mscx
- mtest/musicxml/io/testInferredCredits1_ref.mscx
- mtest/musicxml/io/testInferredCredits2_ref.mscx
- mtest/musicxml/io/testLyricBracket_ref.mscx
- mtest/musicxml/io/testLyricPos_ref.mscx
- mtest/musicxml/io/testPartNames_ref.mscx
- mtest/musicxml/io/testPlacementDefaults_ref.mscx
- mtest/musicxml/io/testSecondVoiceMelismata_ref.mscx
- mtest/musicxml/io/testTextOrder_ref.mscx
> Set lyric position precisely on XML import

- importexport/musicxml/importmxmlpass1.cpp
Backport of one forgotten commit from #19972
> Override text style for composer credit

- libmscore/layout.cpp
> Fix crash during layout if system has no measures

- libmscore/undo.cpp
Backport of #21955
Resolves: [musescore#21914](https://www.github.com/musescore/MuseScore/issues/21914)
> Fix GH#21914: Update chords when loading style file

- libmscore/chordrest.cpp
- libmscore/keyfinder.cpp
- libmscore/measure.cpp
- libmscore/segment.cpp
- libmscore/shape.cpp
- libmscore/skyline.cpp
- mscore/chordview.cpp
- mscore/drumview.cpp
- mscore/pianoroll/pianoview.cpp
and remove unneeded includes which QtCreator warns about
a similar change had been done to master recently
> Replace large 'magic' double values with `DBL_MAX`

- libmscore/score.cpp
Resolves: [musescore#22058](https://www.github.com/musescore/MuseScore/issues/22058) and [musescore#22061](https://www.github.com/musescore/MuseScore/issues/22061)
Backport of #22060
> Fix GH#22058 and GH#22061: Fix issues with Copy lyrics to clipbpard

- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testPlacementDefaults_ref.mscx
- mtest/musicxml/io/testTextOrder_ref.mscx
> Infer tempo text based on a set of words on XML import

- importexport/musicxml/importmxmlpass1.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testInferredCredits1_ref.mscx
- mtest/musicxml/io/testInferredCredits2_ref.mscx
> Refine spacing in XML header vboxes

- importexport/musicxml/exportxml.cpp
> Fix leaving loop to early

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testBackupRoundingError_ref.mscx
- mtest/musicxml/io/testInferredTempoText_ref.mscx
> Untick 'Follow written tempo' for verbal tempo indications on XML import

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testPlacementDefaults_ref.mscx
> Untick 'Follow written tempo' for inferred text too

- importexport/musicxml/importmxmlpass1.cpp
- mtest/musicxml/io/testCopyrightScale.xml
- mtest/musicxml/io/testCopyrightScale_ref.mscx
- mtest/musicxml/io/tst_mxml_io.cpp
> Scale header and footer font size to fit within margins

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testStaffSize.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> MusicXML: add support for staff-size

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlnotepitch.cpp
- mtest/musicxml/io/testAccidentals3.xml
- mtest/musicxml/io/testCueGraceNotes_ref.xml
- mtest/musicxml/io/testIncompleteTuplet_ref.xml
- mtest/musicxml/io/testNoteTuning_ref.xml
Resolves: [#21847](https://www.github.com/musescore/MuseScore/issues/21847)
Came up in  https://musescore.org/en/node/361415
'Backport' of https://github.com/musescore/MuseScore/pull/21835 (actually this here existed first)
> Don't bracket accidentals if the XML says not to

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxml.cpp
- importexport/musicxml/importmxml.h
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- importexport/musicxml/importxml.cpp
- importexport/musicxml/musicxml.h
- importexport/musicxml/musicxmlfonthandler.cpp
- importexport/musicxml/musicxmlfonthandler.h
- importexport/musicxml/musicxmlsupport.cpp
- importexport/musicxml/musicxmlsupport.h
- mtest/musicxml/io/testBreathMarks.xml
- mtest/musicxml/io/testNoteAttributes2_ref.xml
"Backport" of #20370 (actually this here existed first)
> More MusicXML fixes and improvements

- importexport/bww/importbww.cpp
Backport of #21796
Resolves: [musescore#16833](https://www.github.com/musescore/MuseScore/issues/16833)
> Fix GH#16833: BWW import - clef and tempo

- build/ci/macos/notarize.sh
Resolves: #293
May resolve: #118
> Fix macOS notarization

- global/settings/types/preferencekeys.h
- importexport/musicxml/importmxmlpass1.cpp
- libmscore/style.cpp
- mscore/preferences.cpp
- mtest/libmscore/compat206/frame_text2-ref.mscx
- mtest/musicxml/io/testCopyrightScale_ref.mscx
- mtest/musicxml/io/testInferredCrescLines2_ref.mscx
- mtest/musicxml/io/testInferredCrescLines_ref.mscx
- mtest/musicxml/io/testNoteAttributes2_ref.mscx
> Change default style to have copyright on 1st page only

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testBreaksImplExpl_all_ref.xml
- mtest/musicxml/io/testBreaksImplExpl_manual_ref.xml
- mtest/musicxml/io/testBreaksImplExpl_no_ref.xml
- mtest/musicxml/io/testBreaksSystem_manual_ref.xml
- mtest/musicxml/io/testBreaksSystem_no_ref.xml
- mtest/musicxml/io/testColorExport_ref.xml
- mtest/musicxml/io/testDirections1_ref.xml
- mtest/musicxml/io/testDirections2.xml
- mtest/musicxml/io/testFormattedThings.xml
- mtest/musicxml/io/testMaxNumberLevel_ref.xml
- mtest/musicxml/io/testSwing_ref.xml
- mtest/musicxml/io/testSystemDirection.xml
- mtest/musicxml/io/testTextLines_ref.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> Import & export system=only-top for XML directions

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlnotepitch.cpp
- importexport/musicxml/importmxmlpass1.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importxmlfirstpass.cpp
> Reduce use of auto in XML import and export

- libmscore/bsp.cpp
> Resolve inefficiency in BspTree

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
Backport of #22709
Revealed a missing part from an earlier backport of #10412, so I added that too
> Fix nonsense warnings in MusicXML

- libmscore/edit.cpp
Backport of ~#22219~ #22279
Plus some cleanup on the includes
Resolves (partially): [musescore#21049](https://www.github.com/musescore/MuseScore/issues/21098), [musescore#21098](https://www.github.com/musescore/MuseScore/issues/21098) and [musescore#21501](https://www.github.com/musescore/MuseScore/issues/21501) (only the last seems to apply to Mu3)
> Fix GH#21501: crash on insert measures at start

- libmscore/layout.cpp
Backport of #22841
Resolves: [musescore#20742](https://www.github.com/musescore/MuseScore/issues/20742)
> Fix GH#20742: Fix double codas on MMRs

- importexport/musicxml/exportxml.cpp
- mtest/musicxml/io/testInvisibleNote.mscx
- mtest/musicxml/io/testInvisibleNote_ref.xml
- mtest/musicxml/io/tst_mxml_io.cpp
Backport of #22864
Resolves: [musescore#21193](https://www.github.com/musescore/MuseScore/issues/21193)
> Fix: GH#21193: Export invisible stem as no stem

- importexport/musicxml/importmxmlpass2.cpp
> Tempo inference update

- importexport/musicxml/exportxml.cpp
- mtest/musicxml/io/testHarmony7_ref.xml
> MusicXML: mark linked staves when writing staff-details

- importexport/musicxml/exportxml.cpp
> MusicXML: export dot placement

- libmscore/read206.cpp
- libmscore/tuplet.cpp
- libmscore/tuplet.h
Backport of #22699
Resolves: [musescore#22696](https://www.github.com/musescore/MuseScore/issues/22696)
> Fix GH#22696: Number inherits tuplet color

- importexport/musicxml/exportxml.cpp
- libmscore/figuredbass.cpp
- mtest/musicxml/io/testDivisionsDuration.xml
- mtest/musicxml/io/testIncompleteTuplet_ref.xml
- mtest/musicxml/io/testTuplets10.xml
- mtest/musicxml/io/tst_mxml_io.cpp
Backport of #22977
Resolves: [musescore#22344](https://www.github.com/musescore/MuseScore/issues/22344)
> Fix GH#22344: calculate divisions and duration using Fractions

- importexport/guitarpro/importptb.cpp
> Fix ptb import crash

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxml.cpp
- importexport/musicxml/importmxmlpass1.cpp
- importexport/musicxml/musicxmlsupport.cpp
- importexport/musicxml/musicxmlsupport.h
- mtest/musicxml/io/testKeysig2.xml
- mtest/musicxml/io/testPartNames2.xml
- mtest/musicxml/io/testTextLines_ref.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> MusicXML: Add support for part-name-display

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testColors.xml
> MusicXML: set all note components invisible

- libmscore/note.cpp
> Set custom noteheads to normal on non drumset staves

- libmscore/excerpt.cpp
Backport of #22839
Resolves: [musescore#21962](https://www.github.com/musescore/MuseScore/issues/21962)
> Fix GH#21962: Clone measure elements when cloning staff

- libmscore/element.cpp
- libmscore/jump.cpp
- libmscore/marker.cpp
- libmscore/measure.cpp
- libmscore/navigate.cpp
- libmscore/segment.cpp
- libmscore/segment.h
- libmscore/spanner.cpp
- libmscore/system.cpp
- mscore/palette.cpp
- mscore/timeline.cpp
- mtest/libmscore/note/tst_note.cpp
Backport of #22941
Not really needed on Mu3, except for keeping the code in sync, with one exception
> Fix wrong endElement for LyricsLine

- importexport/guitarpro/importgtp-gp4.cpp
> Fix: import gp4 crash

- importexport/musicxml/importmxmlpass1.cpp
- mtest/musicxml/io/testInferredRights.xml
- mtest/musicxml/io/testInferredRights_ref.mscx
- mtest/musicxml/io/tst_mxml_io.cpp
> Correct XML credits

- importexport/musicxml/importmxmlpass2.cpp
(Small) part of #23231 / https://github.com/Jojo-Schmitz/MuseScore/pull/506
> Check for non-breaking space in XML regexes

- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testInferredFingerings.xml
- mtest/musicxml/io/testInferredFingerings_ref.mscx
> Infer 'shift' fingering on XML import

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testDuplicateInstrChange.xml
- mtest/musicxml/io/testDuplicateInstrChange_ref.mscx
- mtest/musicxml/io/tst_mxml_io.cpp
> Don't add redundant instrument changes on XML import

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testBarlineLoc.xml
- mtest/musicxml/io/testBarlineLoc_ref.mscx
- mtest/musicxml/io/tst_mxml_io.cpp
> Use XML barline location correctly

- share/instruments/instruments.xml
> Update Percussion Hand Cymbals

- global/log.h
> Assertion macros: output file and line in standard format

- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testInferFraction.xml
- mtest/musicxml/io/testInferFraction_ref.mscx
- mtest/musicxml/io/tst_mxml_io.cpp
> Format fractions nicely on XML import

- .github/workflows/ci_macos.yml
- CMakeLists.txt
- build/ci/macos/setup.sh
as the the macOS 11 runner is going to get removed by 28Jun2024
> Update Mac CI build environment

- libmscore/note.cpp
> Fix crash when dragging note vertically beyond MIDI range

- libmscore/cmd.cpp
- libmscore/element.cpp
- libmscore/lyrics.cpp
- libmscore/note.cpp
Backport of #23734
Resolves: [musescore#23733](https://wwwgithub.com/musescore/MuseScore/issues/23733)
> Reset leading space on ctrl+r and reset score

- libmscore/ledgerline.cpp
> Set ledger line mag value equal to its parent chord

- importexport/guitarpro/importgtp.cpp
Added a similar check that already exists for other GP readers
Backport of #23748
> Fixed a potential crash in GuitarPro import

- importexport/musicxml/exportxml.cpp
- mtest/musicxml/io/testTextLines.mscx
- mtest/musicxml/io/testTextLines_ref.xml
Backport of #23730
Resolves: [musescore#21390](https://www.github.com/musescore/MuseScore/issues/21390)
> Fix GH#21390: Export text from text lines with line hidden

- share/locale/instruments_pl.ts
- share/locale/mscore_pl.ts
- share/locale/tours_pl.ts
Update Polish Translation
Many fixes.
Greetings,
Gootector
> Update Polish Translation

- importexport/musicxml/importmxmlpass2.cpp
> Fix nested tuplet crash

- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_windows.yml
- .github/workflows/check_visual_tests.yml
- .github/workflows/translate_lupdate_tx_push.yml
- .github/workflows/translate_tx_pull_to_s3.yml
- build/ci/linux/build.sh
- build/ci/linux/package.sh
- build/ci/macos/build.sh
- build/ci/macos/package.sh
- build/ci/tools/make_build_mode_env.sh
- build/ci/tools/osuosl/publish.sh
- build/ci/windows/build.bat
- build/ci/windows/package.bat
> GitHub Actions: Tidy workflow files

- libmscore/cmd.cpp
Backport of #23810
Resolves: [musescore#23809](https://www.github.com/musescore/MuseScore/issues/23809)
> Fix GH#23809: Note change by up / down key respect double and triple accidentals (if present)

- audio/exports/exportmidi.cpp
Backport of #21541
Resolves: [musescore#15925](https://www.github.com/musescore/MuseScore/issues/15925)
> Fix GH#15925: Include lyrics in MIDI export

- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_windows.yml
- .github/workflows/translate_lupdate_tx_push.yml
> GitHub Actions: Replace github.event.inputs.X with inputs.X

- .github/workflows/build_all.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_windows.yml
> CI: Add 'Build: All' workflow and platforms input

- .github/workflows/build_all.yml
- .github/workflows/deploy.yml
- build/ci/release/collate_release_binaries.sh
- build/ci/release/make_tag_name.sh
> CI: Add deployment workflow

- .github/workflows/update_release_info.yml
- build/ci/release/append_release_to_previous_releases.py
- build/ci/release/correct_release_info.py
- build/ci/release/get_file_from_s3.sh
- build/ci/release/make_empty_release_info_file.sh
- build/ci/release/make_previous_releases_notes.sh
- build/ci/release/make_release_info_file.sh
- build/ci/release/push_file_to_s3.sh
> More CI updates

- audio/exports/exportmidi.cpp
Backport of #24171
Resolves: [musescore#24168](https://www.github.com/musescore/MuseScore/issues/24168)
> Fix GH#24168: Correctly export repeat lyrics

- mscore/file.cpp
Backport of #16034
Resolves: [musescore#15861](https://www.github.com/musescore/MuseScore/issues/15861)
Resolves: #587
> Fix GH#15861: Printing scores prints square the number of requested copies

- libmscore/chord.cpp
- libmscore/chord.h
- libmscore/layout.cpp
> Correct accidentals for cross-staff grace notes

- mscore/file.cpp
> Fix GH#601:  MS 3.7 doesn't export PDF in landscape format

- .github/workflows/build_all.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_windows.yml
- build/ci/tools/make_build_mode_env.sh
- build/ci/tools/make_build_number.sh
Resolves: https://github.com/Jojo-Schmitz/MuseScore/pull/605#issuecomment-2323527135
> Some changes to CI, esp. the artifact names

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testTupletTie.xml
- mtest/musicxml/io/testTupletTie_ref.mscx
- mtest/musicxml/io/tst_mxml_io.cpp
Backport of #24416
Resolves: [musescore#24357](https://www.github.com/musescore/MuseScore/issues/24357)
> Fix GH#24357: Fix XML import of tied tuplets

- mscore/musescore.cpp
- mscore/musescoredialogs.cpp
- mscore/musescoredialogs.h
> [Cmd: insert/append measure] dialog should have spinbox highlighted by default ready for keyboard entry

- libmscore/layout.cpp
- libmscore/stringdata.cpp
> Fix tab error for 8va, 15va etc. ottava line usage

- libmscore/cmd.cpp
Backport of 20240
Resolves: #572
> Allow up-down edit on the ending note of bend in TAB staves

- importexport/guitarpro/importgtp-gp4.cpp
- importexport/guitarpro/importgtp-gp5.cpp
- mtest/guitarpro/brush.gp5-ref.mscx
Backports of #23229 and #24581
> gp-import: fixed arpeggio duration for gp5 and gp4 files

- importexport/guitarpro/importgtp-gp5.cpp
- mtest/guitarpro/brush.gp5-ref.mscx
> gp-import: fixed arpeggio direction for gp5

- libmscore/property.h
> Fix crash accessing uninitialized properties

- libmscore/edit.cpp
> Add clefs to parts & linked staves when copying

- libmscore/edit.cpp
Backport of #24571
Resolves: [musescore#24434](https://www.github.com/musescore/MuseScore/issues/24434)
> Fix GH#24434: Add ambitus to parts

- mscore/musescore.cpp
- mscore/musescore.h
- mscore/musescoredialogs.cpp
- mscore/preferences.cpp
- mscore/prefsdialog.cpp
- mscore/shortcut.cpp
as neither works or is provided by this fork
> Disable Feedback and Check for updates

- libmscore/style.cpp
> Ignore new 4.5 style setting

- libmscore/excerpt.cpp
Backport of #24925, also fix some clazy warnings
Resolves: [musescore#24895](https://www.github.com/musescore/MuseScore/issues/24895)
> Clone barlines to part

- importexport/guitarpro/importgtp-gp5.cpp
- mtest/guitarpro/volta.gp5-ref.mscx
Backport of #24981 and fix some clazy warnings, one of which revealed a memory leak
I'm not convinced about its correctness though...
> Fix gp5 voltas import

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testIncompleteTuplet_ref.xml
- mtest/musicxml/io/testNoteAttributes1.xml
- mtest/musicxml/io/testNotesRests1.xml
- mtest/musicxml/io/testRestNotations_ref.xml
Backport of  #25040
Resolves: [musescore#25012](https://www.github.com/musescore/MuseScore/issues/25012)
> Fix inferring measure rests & read the measure attribute

- share/templates/03-Chamber_Music/01-String_Quartet.mscx
- share/templates/03-Chamber_Music/02-Wind_Quartet.mscx
- share/templates/03-Chamber_Music/03-Wind_Quintet.mscx
- share/templates/03-Chamber_Music/04-Saxophone_Quartet.mscx
- share/templates/03-Chamber_Music/05-Brass_Quartet.mscx
- share/templates/03-Chamber_Music/06-Brass_Quintet.mscx
Backport of #25091
Resolves: [musescore#24916](https://www.github.com/musescore/MuseScore/issues/24916)
> Fix GH#24916: Disable concert pitch in chamber music templates

- importexport/musicxml/importmxmlpass2.cpp
'Backport' of #25112 (actually this here existed first
Resolves: [musescore#25103](https://www.github.com/musescore/MuseScore/issues/25103)
> Fix GH#25103: Infer `<type>` from <`duration>` in MusicXML import

- libmscore/edit.cpp
Backport of #25445
Resolves: [musescore#25216](https://www.github.com/musescore/MuseScore/issues/25216)
> Fix missing ties in parts on regroup rhythms

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testHarmony6_ref.xml
- mtest/musicxml/io/testHarmony9.xml
- mtest/musicxml/io/testNumerals.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> MusicXML: add support for numerals

- share/locale/mscore_pl.ts
Update Polish translation
Greetings,
Gootector
Resolves: *(direct link to the issue)*
*(short description of the changes and the motivation to make the changes)*
> Update Polish translaion

- libmscore/iname.cpp
- libmscore/system.cpp
- mscore/editstyle.cpp
Backport of #25606 plus fixing a clazy warning
Resolves: [musescore#25204](https://www.github.com/musescore/MuseScore/issues/25204)
For some strange reason this doesn't seem to work though?!? Same code does work in Mu4...
> Fix GH#25204: Color of instruments not respected

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
> [MusicXML] improve import/export of notations

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testHarmonMutes.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> [MusicXML] full support for Harmon mutes

- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testColors.xml
> [MusicXML] add import of breath color

- libmscore/mcursor.cpp
- mscore/noteGroups.cpp
- share/instruments/instruments.xml
> Fix GH#733:  Master Palette crashes without stock instruments.xml

- .github/workflows/build_macos.yml
- build/package_mac
* Prevent useless duplicate warning reg. notarization
* Quote a shell variable (sync with master)
> Some build improvements

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testHoles.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> [MusicXML] Add full support for holes element

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testHandbells.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> [MusicXML] Add full support for hand bells

- libmscore/edit.cpp
Resolves: https://musescore.org/en/node/373687
> Fix crash when pasting multimeasure rest to first measure

- mscore/preferences.cpp
and allow changing it in advanced preferences
Resolves: https://musescore.org/en/node/373664
> Disable update check

- libmscore/layout.cpp
- libmscore/measure.cpp
Backport of #25420 and #25865
Resolves: [musescore#22256](https://www.github.com/musescore/MuseScore/issues/22256)
Resolves: [musescore#19759](https://www.github.com/musescore/MuseScore/issues/19759)
> Add courtesy keysig to last measure even if it is followed by frame

- mscore/scoreview.cpp
> Fix GH#673: Repeat Measure leads to crash

- libmscore/rest.cpp
- libmscore/score.cpp
Backport of #25537 plus fixing most clazy warnings
Resolves: [musescore#17082](https://www.github.com/musescore/MuseScore/issues/17082)
> [techdebt] Addresses code issues identified in issue GH#17082

- .github/workflows/build_macos.yml
' Backport' of #26309 (actually this here existed first)
> Notarize macOS builds for all but PRs

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testTimesig4.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> [MusicXML] Add support for single number time signature

- importexport/musicxml/exportxml.cpp
- mtest/musicxml/io/testLineDetails.mscx
- mtest/musicxml/io/testLineDetails_ref.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> [MusicXML] export staff line details

- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testColors.xml
Backport of #26495, 2nd commit
> MusicXML Import - Arpeggios don't have their color imported

- share/styles/legacy-style-defaults-v1.mss
- share/styles/legacy-style-defaults-v3.mss
- share/styles/legacy-style-defaults-v302.mss
> Give style defaults correct MuseScore version

- audio/exports/exportmidi.cpp
> Add RehearsalMark to MIDI export as Markers

- aeolus/prbsgen.h
- mscore/seq.cpp
Text fix: UK English -> US English
Greetings,
Gootector
Resolves: *(direct link to the issue)*
*(short description of the changes and the motivation to make the changes)*
> Text fix: UK English -> US English

- importexport/musicxml/importmxmlpass2.cpp
> [MusicXML] add forgotten technical indications

- importexport/musicxml/importmxmlpass2.cpp
> [MusicXML] read non-arpeggiate color and avoid double checks

- libmscore/sym.cpp
upstream master has it already
> Add "thinThickBarlineSeparation" to `engravingDefaults`

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testGlissandoLines.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> [MusicXML] Add glissando line styles

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
> [MusicXML] add support for guitar tap

- importexport/musicxml/exportxml.cpp
- mtest/musicxml/io/testNoteAttributes2_ref.xml
> [MusicXML] rework ornaments export

- importexport/musicxml/exportxml.cpp
> [MusicXML] clean-up and unify code

- mscore/chordview.cpp
- mscore/drumview.cpp
- mscore/pianoroll/pianoview.cpp
and same in two more similar places, in chord- and drum view
Resolves: #850
> Fix GH#850: Piano roll editor shift horizontal scroll

- share/locale/mscore_fr.ts
> Update French translations

- importexport/musicxml/importmxmlpass2.cpp
> [MusicXML] import shake ornament

- importexport/musicxml/importmxmlpass2.cpp
- libmscore/hairpin.cpp
> Fix GH#867: Hairpins saved in position above re-opens in position below.

- importexport/bww/lexer.cpp
- importexport/bww/lexer.h
- importexport/bww/symbols.cpp
- importexport/bww/symbols.h
> Fix probable bug in BWW lexer

- libmscore/repeatlist.cpp
- libmscore/scorediff.cpp
along with another similar stupid mistake (of mine!) in the handling of repeat lists
Resolves: #856
> Fix score comparison tool for MuseScore versions using Qt 5.15

- libmscore/chord.cpp
fixes an issue of a backport of #9774, along with fixing clazy warnings
Resolves: https://musescore.org/en/node/377801
> Fix #377801: Crash when flipping stem direction on a rest

- mscore/editstyle.cpp
- mscore/musescore.cpp
basically a different (and apparently correct) way of fixing clazy warnings than those from 618f6b6, along with another similar fix
Resolves: #679
> Fix GH#679: Better alternative

- libmscore/clef.cpp
- libmscore/clef.h
- mscore/menus.cpp
Resolves: https://musescore.org/en/node/375571
'Backport' of #26858 (actually this here existed first)
> Fix #375571: Add "G clef ottava bassa with C clef"

- libmscore/read114.cpp
Resolves: [musescore#27822](https://www.github.com/musescore/MuseScore/issues/27822)
> Fix import of 1.x closed voltas

- mscore/pianotools.cpp
> Fix Virtual Piano Freezes

- .github/workflows/build_all.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_windows.yml
- .github/workflows/check_visual_tests.yml
- .github/workflows/publishdev.yml
- build/ci/linux/Dockerfile
- build/ci/linux/build.sh
- build/ci/linux/package.sh
- build/ci/linux/runmtests.sh
- build/ci/linux/setup.sh
- build/ci/linux/tools/make_appimage.sh
- build/ci/tools/osuosl/publish.sh
continues #881
Have not tested arm builds yet. (If you're trying userland on android, dev/fuse need root)
PR checks might fail because of workflow script changes. see tests on my copy https://github.com/fp22june/MuseScore/actions/runs/14867539002
> Add official ARMhf and ARM64 Linux github actions

- .github/workflows/build_linux.yml
continues #938
github parse the expanded slash in ADD_INFO as dir
also fixed a minor log typo spotted
>  Fix Linux build failures in PRs with "foo / bar" in title

- mscore/scoreview.cpp
> Fix "Find" to move view point to found measure, page, rehearsal mark

- importexport/musicxml/importmxmlpass1.cpp
- importexport/musicxml/importmxmlpass1.h
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
Backport of #28052
Resolves: [musescore#27961](https://www.github.com/musescore/MuseScore/issues/27961)
> [MusicXML] Improve tempo import from Dorico

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
> [MusicXML] Import/export rehearsal mark alignment

- libmscore/segment.cpp
- mtest/musicxml/io/testLayoutCleanup2_ref.mscx
- mtest/musicxml/io/testWedgeOffset_ref.mscx
This reverts commit 1c3e9b997d66681f039e1a2d95f319e7162f8639.
Resolves: #932
> Revert "improve horizontal spacing & vertical alignment"

- fonttools/genft.cpp
- libmscore/barline.cpp
- libmscore/sym.cpp
> Fix position of `repeatDot` for the external fonts Ekmelos and Emmentaler

- mtest/musicxml/io/testBreaksManual_all_ref.xml
- mtest/musicxml/io/testBreaksManual_no_ref.xml
- mtest/musicxml/io/testBreaksPage_all_ref.xml
- mtest/musicxml/io/testBreaksPage_manual_ref.xml
- mtest/musicxml/io/testBreaksPage_no_ref.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> Musicxml tests updates

- libmscore/utils.cpp
- mscore/timesigproperties.cpp
Backport of #26107 plus some more (-, /, =), just because I don't see why not ;-)
> Add multiplication sign (and some more) for time signatures

- libmscore/property.cpp
- libmscore/property.h
- libmscore/timesig.cpp
- libmscore/timesig.h
- mscore/inspector/inspector.cpp
- mscore/plugin/api/elements.h
> Remove `globalSig`

- importexport/musicxml/exportxml.cpp
Backport of #28304
Resolves: [musescore#28290](https://www.github.com/musescore/MuseScore/issues/28290)
> Fix GH#28290: fix dots on tab chords

- build/ci/linux/tools/make_appimage.sh
> [CI] fixed download appimagetool

- audio/exports/exportmp3.cpp
- libmscore/part.cpp
- libmscore/read302.cpp
- libmscore/staff.cpp
- libmscore/style.cpp
- libmscore/style.h
ignoring new tags, acting on changed defaults
> Mu4.6 compatibility

- importexport/musicxml/exportxml.cpp
> [MusicXML] improve placement export

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testColors.xml
> [MusicXML] Unify color import

- libmscore/tie.cpp
by syncing `Tie::calculateDirection()`'s code with upstream/master
Resolves: #1018
> Fix GH#1018: Crash on Split Measure, Undo

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testDynamics2.xml
> [MusicXML] import dynamics color and enclosing
