Jojo-Schmitz/MuseScore

- libmscore/element.cpp
- libmscore/line.cpp
to any but the top part/instrument, if parts have been generated, and another on saving after having added it.
Fixes https://musescore.org/en/node/321902
> Fix #321902: Crash on adding note-anchored lines

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testArticulationsCombined_ref.mscx
- mtest/musicxml/io/testCueNotes3_ref.mscx
Articulations without placement or type attributes import as "chord automatic".
Articulations with placement or type attributes import as "above chord" or "below chord".
Backport of #16751 to Mu3
Resolves: #16658
> Fix GH#16658: Position of articulations is incorrect in imported XML files from Reaper

- libmscore/edit.cpp
Resolves: #15727 (but for 3.x, backport of #16770)
> [MU3] Fix GH#15727: Crash on transpose of specific 3.6 score

- libmscore/cmd.cpp
Backport of #15307, albeit in a slightly different way
Resolves: #15284
> Fix GH#15284: Disabled accidentals on tablature, fixing bug where it would always result in C9 or variation upon it

- importexport/musicxml/exportxml.cpp
from `{ "staccato", "soft-accent", "tenuto" }` to `{ "soft-accent", "detached-legato" }`, and changing the order a bit to match how #16828 is doing it for master now.
Adds to an earlier backport of #8190 to 3.x
> Changing MusicXML export of "Soft Accent Tenuto Staccato"

- libmscore/measure.cpp
Idea stems from https://musescore.org/en/node/347533
> Add backwards compatibilty for measure repeats

- libmscore/image.cpp
Fixes #95, to fix an earlier fix from #7871 (a 3.x version of #7740 for master) that was supposed to fix https://musescore.org/en/node/318772
> Fix GH#95: Loss of image

- libmscore/system.cpp
Backport of #16840
Resolves: https://musescore.org/en/node/346638
Same issue (and fix) in Mu3 and Mu4 (so not a regression)
To reproduce the crash select a title frame and press Shift+Ctrl+Alt+Left (shortcut for "Select previous in-staff element")
> Fix #346638: Crash - select title frame > previous in-staff element

- libmscore/style.cpp
The tags for text style names are all lower case in 4.x, but start with a capital letter in 3.x (and earlier).
So when reading a 4.x (mscx) file in 3.x, all test style types are 'detected' as `""`, `Tid::DEFAULT`. Esp. annoying for the texts in the title frame.
Making the comparison case-insensitive should fix this and not harm otherwise.
> Detect text style types correctly when reading 4.x mscx files

- libmscore/layout.cpp
Backport of #17302
Resolves: #15108
> Fix crash when Ctrl+A in 206 score with Glissandos without end element

- libmscore/cmd.cpp
- libmscore/select.cpp
- libmscore/select.h
- mscore/scoreview.cpp
Sort the notes by string, so that moved notes don't block each other.
Backport of #17410, converting `Selection::uniqueNotes()` from using `QList` to `std::list` in the due course, as that's how Mu4 does it too, and here avoids the use of the obsolete `QList::toStdList()`. While at it, doing the same for `Selection::uniqueElements()`.
> Fix GH#10403: Moving notes between strings

- importexport/musicxml/exportxml.cpp
This updates MusicXML export to correctly export turn ornamentTurnSlash.
Backport of #17300
> [MusicXML] Export turn with slash

- libmscore/textbase.cpp
- libmscore/textbase.h
- libmscore/textedit.cpp
- libmscore/textedit.h
Backport of #15529. Mu3 doesn't give a finger but a wrongly styled dynamics glyph
Resolves: #15170 for 3.x
> Fix #15170: Fixed MU giving the finger on deleting letters in dynamics

- libmscore/letring.cpp
- libmscore/line.cpp
- libmscore/palmmute.cpp
at least a potential crash. Same for Let Ring.
Backport of #17682
> Fix PalmMute crash

- libmscore/textbase.cpp
- libmscore/textedit.cpp
Backport of #17739
Resolves: #15629, although I'm not yet sure whether 3.x is affected by that in the first place
> Fix losing spaces when in-between symbols

- .github/workflows/ci_macos.yml
- build/ci/macos/setup.sh
- build/package_mac
Trying to solve the packaging problem with Qt5.15.2
Some softwares of the virtual machine not directly used for the compilation were deleted.
> free disk space for MacOS CI compilation

- libmscore/range.cpp
Backport of #15129
Resolves: #132
Came up in https://musescore.org/en/node/351689
> Fix GH#15090: add annotations within tuplet consistent with non-tuplet segments

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/musicxmlfonthandler.cpp
- libmscore/textbase.cpp
- mtest/musicxml/io/testInvalidLayout.mscx
- mtest/musicxml/io/testInvalidLayout_ref.xml
- mtest/musicxml/io/tst_mxml_io.cpp
Resolves: https://musescore.org/en/node/293441 for 3.x, backport of #17848 / #18056
> Fix #293441: Invalid XML export: direction-type is missing child element

- libmscore/note.cpp
Backport of #17705
Resolves: #17502
> Fix GH#17502: Exclude tab staves from clef change recalculation shenanigans

- libmscore/page.cpp
- mscore/musescore.cpp
> Fix GH#145: Crash going from page to continuous view and then clicking on score element

- libmscore/style.cpp
> Another 4.x compatibility fix, "instrument_excerpt" vs. "Instrument Name (Part)"

- share/locale/mscore_ja.ts
> Corrected access key in Japanese translation

- libmscore/hairpin.cpp
- libmscore/line.cpp
- libmscore/style.cpp
Resolves: #175. Actually their lines just just go invisible, having no line style at all. Same issue with newly added hairpins, voltas, ottavas let ring and palm mute lines
Also resolves #179 for harpins (for others it got fixed earlier already)
> Hairpins, ottavas, voltas, pedal, let ring and palm mute lines can get lost on Mu4 mscz import, hairpins loose their custom line style

- importexport/musicxml/exportxml.cpp
- mtest/musicxml/io/testLines4_ref.xml
Export T hook endings on dashed lines to MusicXML.
Backport of #19455
Resolves: #18451
> Fix GH#18451: MusicXML: export T hook

- mscore/exportdialog.cpp
If you select the option "No system or page breaks" (or "System and page breaks" or "Manually added system and page breaks only"), that setting gets stored in MuseScore3.ini under `musicXML\exportBreaks`, and stays there, even if later you change to "All layout", which uses a different setting. `musicXML\exportLayout`, and really should include "Systems and page breaks"
But the contrary is true too, once "All layout" has been chosen, it stays chosen indefinitely, without regards to the system and page break settings, instead of unsetting "All layout".
As these are radio buttons in the export dialog and the preferences, those options are really mutaually exclusive, or rather should be... Seems in preferences it is handled correctly, but not in the export dialog.
Mu4 (at least 4.1.1) does …
> [MusicXML] Export system/page breaks along with the rest of the layout

- libmscore/textlinebase.cpp
For lines with a 45° angle though use round caps
Resolves: #190
> Fix GH#190: Hooks should be drawn as square cap

- libmscore/part.cpp
Resolves: #17720
Resolves: #19698
It is questionable though how much sense this makes; it will enable the user to open the score, but it is still corrupted so it is very likely that a crash will occur anyway later while working with it.
Backport of #19708
Prevents the crash (actually an assertion failure) on opening these scores, but unlike the original PR still crashes (dies on a SIGSEGV) when opening the broken part (Alto Sax and Organ, respectively).
OTOH you can at least open the score and fix it, quite a bit better than crashing on loading it.
[ajr_Worlds_Smallest_Violin.zip](https://github.com/Jojo-Schmitz/MuseScore/files/12898550/ajr_Worlds_Smallest_Violin.zip)
[Joyful we adore thee.zip](https://github.com/Jojo-Schmitz/MuseScore/files/12898228/Joyful.we.adore.thee.zip)
> Prevent crash when opening score with `Part` with no staves

- main/CMakeLists.txt
Resolved comment: https://github.com/musescore/MuseScore/issues/17247#issuecomment-1763501983
Backport of #19726
Not sure whether it is needed for Mu3, but it sure doesn't harm either.
> Install qoffscreen platform plugin on Windows

- libmscore/beam.cpp
Resolves: #19398
Backport of #19727
> Fix GH#19398: Make sure "reset" command for Beam is fully undoable

- mscore/exportdialog.ui
- mscore/fotomode.cpp
- mscore/prefsdialog.ui
so that Preferences dialog, Export dialog and Foto mode dialog agree on min., max., default and decimals.
Resolves: #12772 (sort of, and in an entirely different way)
> Harmonize DPI settings for PDF and PNG export

- libmscore/transpose.cpp
- libmscore/utils.cpp
- libmscore/utils.h
If the first key signature on a system is a change to the measure before, it will be transposed. Otherwise it will be left untouched.
Resolves: #18404
Backport of #18530
> Fix GH#18404: Transpose tool will only transpose initial key signature on a system if there is a key change

- libmscore/tempotext.cpp
Resolves: #19819
`Backport' of #19822
> Fix GH#19819: Allow approximately equal signs to work on tempo text

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testExcessHiddenStaves_ref.mscx
- mtest/musicxml/io/testHiddenStaves.xml
- mtest/musicxml/io/tst_mxml_io.cpp
Backport of #11953
Resolves: https://musescore.org/en/node/307530
Introduces #16135 though, so needs a(n at least partial) backport of #18556, resp. #17033, #17035 and #17118 too, to resolve #16497 (optional and rather unrelated), #16135 and #17037 (optional and rather unrelated).
And that in turn should get accompanied by #19901.
So that's what this PR does also ;-)
> Fix #307530: MusicXML export for hidden staves

- libmscore/layout.cpp
- vtest/gen
- vtest/gen.bat
- vtest/staffEmptiness.mscx
Resolves: #141
Possible fixes:
* Revert "ENG-54: Check spanners when assessing emptiness, part 2", commit 1a0794f and along with it "Fix for voltas and system text lines after "ENG-54, part 2"", commit 41151b6
I do see some value in that ENG-54 fix (check the test score from the commit to see), but for now it causes a major breakage and the issue it fixes isn't fixed in Mu4 either.
* It seems possible to fix it instead. 
Not sure though **why** hairpins need to get excluded here?
Edit: this is because the end of a hairpin that ends at a measure is recodered in the measure **after** the one it ends in.
Downside: it also hides staves that are empty except for hairpins, but as those are pretty meaningless, I guess we can let this pass.
See also #19679
So we're gonna take the 2nd option...
> Fix GH#141: Not hiding staff with subsequent empty measures after crescendo line in measure before

- mscore/file.cpp
- mscore/palette.cpp
via https://musescore.org/en/handbook/3/images I've just learned that BMP and TIF files are supported image formats, but then found that for the frames' "Add image" dialog and Edit > Preferences > Canvas these formats are not being offered.
While for the former "drag'n'drop" is a workaround, for the latter it is to change the filter to "all files".
Backport of #19917
> Properly support BPM and TIFF images for frames and canvas

- libmscore/spanner.cpp
Backport of #20107
Resolves: #19082
> Fix GH#19082: Write location before spanner end on score end

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass1.cpp
- importexport/musicxml/importmxmlpass2.cpp
* Invalid MusicXML exported for time signatures cut time (Bach) and cut triple time
Came in via #7089
Resolves: #20196
* MusicXML import of common and cut time is too strict
Resolves: #20207 
Backport of #20197
> MusicXML fixes for time signatures cut time

- libmscore/element.cpp
- libmscore/style.cpp
* 4.2+ compat: ignore `<eid>` tags, as these cause lots of debug output
* More default style changes, Mu4.2 to Mu3.6/7
And some resetting back to Mu3 defaults, for values that Mu4 resets to its defaults.
* Import Mu4 test styles (as long as they have Mu3 counterparts)
> More Mu4 compatibility

- importexport/musicxml/exportxml.cpp
- mtest/musicxml/io/testMeasureNumberOffset.xml
- mtest/musicxml/io/tst_mxml_io.cpp
Backport of #20511
Resolves: #20490
Important score information which should be included in the first bar of the piece was not being written if the first measures's number is offset.
> Fix GH#20490: Export scores not starting with measure 1 correctly

- libmscore/barline.cpp
Backport of #20443
Resolves: #20045
> Fix GH#20045: Do not check showUnprintable() when rendering irregular measures

- libmscore/layout.cpp
Backport of the 3rd commit of #21063 resp. the 2nd part of #21050
Resolves: #21020
> Fix GH#21020: Check hook is valid before getting width, part #2

- libmscore/chordrest.cpp
Fix GH#14722, part 1: fix Instrument change from palette
Backport of #14802
Resolves: #14722, part 1
Fix GH#14722: Fixed a crash after adding an instrument change element and undoing it (via ctrl + z)
Backport of #14804, 2nd commit
Resolves: #14845
Resolves: #288
> Fix GH#288: Fix Instrument change from palette

- libmscore/edit.cpp
- mscore/pianoroll/pianoview.cpp
- mscore/pianoroll/pianoview.h
A lot of bugfixes for when blocks are being moved around in the PRE.  Should avoid a lot of the problems with notes disappearing.
> 3.x piano roll editor fix note placement

- libmscore/select.cpp
(partial) backport of #21280 (the harmony part)
Resolves: #21175 (the harmony part, bends don't seem to be an issue in Mu3)
> Fix GH#21175: Include fret diagram harmony symbols in range selections

- libmscore/layout.cpp
- libmscore/segment.cpp
* Not layouting spanners on hidden staves, backport of #20798
* Avoid computing horizontal spacing for hidden staves, backport of #20876
Possible todo: Skip computing spacing for hidden elements, backport #20799,
> Some optimizations for invisible staves: not laying spanners nor computing horizontal spacing

- libmscore/cmd.cpp
Backport of #21447
Resolves: #21056
> Fix GH#21056: Don't add empty whole measure rests to second+ voices

- libmscore/layout.cpp
Backport of #21762
Actually this changes the order a bit more than the original PR, but makes that order match between Mu4 and Mu3
Resolves: #21760
> Fix GH#21760: Fret diagrams go before voltas in stacking order

- libmscore/trill.cpp
Backport of #21770
Resolves: #21769
> Fix GH#21769: Correct cross-system trill symbols

- libmscore/element.cpp
- libmscore/element.h
- libmscore/layoutbreak.cpp
- libmscore/measurebase.cpp
Backport of #21730
Resolves: [musescore#21621](https://www.github.com/musescore/MuseScore/issues/21621)
> Fix GH#21621: Use triggerLayoutAll() when updating the measure number property of section breaks

- libmscore/layout.cpp
- libmscore/page.cpp
- libmscore/score.h
- libmscore/scorefile.cpp
- libmscore/system.cpp
- mscore/musescore.cpp
Backports of #21599, #21689 and#21812. Also #21699
Pretty limited use, as AFAIK so far it is used only on musescore.com and/or in the mobile apps.
Shouldn't harm much either...
And maybe there is some use, with my commit that enables Floating mode on Debug builds or when using the -x commandline option to enable experimental features
> Fixes for LayoutMode::FLOAT

- importexport/musicxml/exportxml.cpp
Backport of #21772
Resolves: [musescore#19019](https://www.github.com/musescore/MuseScore/issues/19019)
> Fix GH#19019: Fix empty figured-bass in MusicXML export

- libmscore/note.cpp
Backport of #21858
Resolves: [#21479](https://www.github.com/musescore/MuseScore/issues/21479)
> Fix GH#21479: Accidentals follow note visibility when repitching

- libmscore/segment.cpp
Backport of #20339 (replaced by #21978)
Resolves: [musescore#19535](https://www.github.com/musescore/MuseScore/issues/19535)
> Fix GH#19535: undo redo undo crash

- libmscore/paste.cpp
Backport of #21990
Resolves: [musescore#21786](https://www.github.com/musescore/MuseScore/issues/21786)
> Fix GH#21786: Prevent crash when pasting list selection including hairpins

- libmscore/layout.cpp
Backport of #21997
And remove some superfluous includes, which QtCreator warns about
> Align spanners only when placement matches

- libmscore/layout.cpp
#4  0x00007a53720dd3b2 in std::__glibcxx_assert_fail (... condition=condition@entry=0x60abeae61604 "!this->empty()")
#5  0x000060abeac23e90 in std::vector<Ms::MeasureBase*, std::allocator<Ms::MeasureBase*> >::back
#6  std::vector<Ms::MeasureBase*, std::allocator<Ms::MeasureBase*> >::back
#7  Ms::LayoutContext::getNextPage
> LayoutContext: Fix indexing of empty array

- libmscore/textbase.cpp
Backport of #22209
Resolves: [musescore#20361](https://www.github.com/musescore/MuseScore/issues/20361)
> Fix GH#20361: Clicking the end of a text selection does nothing.

- libmscore/note.cpp
Backport of #22352
Resolves: [musescore#22320](https://www.github.com/musescore/MuseScore/issues/22320)
> Fix GH#22320: Score corrupt after copy/paste whole note and change duration

- libmscore/glissando.cpp
- libmscore/slur.cpp
- libmscore/tie.cpp
Backport of #21347
Resolves: [musescore#16396](https://www.github.com/musescore/MuseScore/issues/16396)
> Fix GH#16396: Tie, Slur, Glissando invisibility/color crossing system breaks

- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testBackupRoundingError_ref.mscx
Backport of #22455, which in turn is a port of #8556 (which got ported to 3.7 earlier), but doesn't replace hanging ties with l.v. articulations, opting instead to simply delete them pending a proper feature.
> Remove hanging ties on XML import

- libmscore/score.cpp
Backport of #22544
Resolves: [musescore#22041](https://www.github.com/musescore/MuseScore/issues/22041)
Resolves: [musescore#22042](https://www.github.com/musescore/MuseScore/issues/22042)
> Ensure harmony channels are added/removed with fret diagrams

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
to match the images on the MusicXML spec website
Backport of #21927
> Improve MusicXML articulations <-> SymId conversion

- libmscore/keysig.cpp
- libmscore/read302.cpp
also ignore the Mu4 tag `<open>` (which even there doesn't seem to do anything usefull
Resolves: #443
> Fix GH#443: Importing Mu4 scores looses key sig of transposing instruments

- libmscore/hairpin.cpp
Backport of #22613
Resolves: [musescore#22384](https://www.github.com/musescore/MuseScore/issues/22384)
> Fix GH#22384: Don't align dynamics when hairpin line isn't visible

- importexport/capella/capella.cpp
- libmscore/chord.cpp
- mtest/capella/io/test1.cap-ref.mscx
- mtest/capella/io/test1.capx-ref.mscx
- mtest/capella/io/test3.cap-ref.mscx
- mtest/capella/io/test3.capx-ref.mscx
- mtest/capella/io/test4.cap-ref.mscx
- mtest/capella/io/test4.capx-ref.mscx
- mtest/capella/io/test5.cap-ref.mscx
- mtest/capella/io/test5.capx-ref.mscx
- mtest/capella/io/test6.cap-ref.mscx
- mtest/capella/io/test6.capx-ref.mscx
- mtest/capella/io/test7.cap-ref.mscx
- mtest/capella/io/test7.capx-ref.mscx
- mtest/capella/io/test8.cap-ref.mscx
- mtest/capella/io/testBarline.capx-ref.mscx
- mtest/capella/io/testEmptyStaff1.capx-ref.mscx
- mtest/capella/io/testEmptyStaff2.capx-ref.mscx
- mtest/capella/io/testPianoG4G5.capx-ref.mscx
- mtest/capella/io/testScaleC4C5.capx-ref.mscx
- mtest/capella/io/testSlurTie.capx-ref.mscx
- mtest/capella/io/testText1.capx-ref.mscx
- mtest/capella/io/testTuplet1.capx-ref.mscx
- mtest/capella/io/testTuplet2.cap-ref.mscx
- mtest/capella/io/testTuplet2.capx-ref.mscx
For some strange reason that also fixes superfluous key signatures.
Resolves: https://musescore.org/de/node/363553
Capella apparently repeats clef, key- and time signature on every start of a system.
If you then remove the system break(s), and that results in the systems to automatically break at a different spot, at the first measure after the previous system break there will be a clef and a key signature, even if it is the same as already active.
This bug annoyed me quite a bit back in the Mu1 days, but it took me until today to get to the bottom of it.
> Fix superfluous clefs after every system break on Capella import

- mscore/data/shortcuts-Mac.xml
- mscore/data/shortcuts.xml
- mscore/data/shortcuts_AZERTY.xml
Backport of #22694
Resolves: [musescore#20650](https://www.github.com/musescore/MuseScore/issues/20650)
> Fix GH#20650: Change mmrest default shortcut

- libmscore/cmd.cpp
- libmscore/edit.cpp
- libmscore/note.cpp
- libmscore/paste.cpp
- libmscore/sym.cpp
- mtest/libmscore/copypaste/copypasteNote12-ref.mscx
- mtest/libmscore/copypaste/copypasteNote12.mscx
- mtest/libmscore/copypaste/copypasteSplit04-ref.mscx
- mtest/libmscore/copypaste/copypasteSplit04.mscx
- mtest/libmscore/copypaste/tst_copypaste.cpp
Backport of #22575
Resolves: [musescore#22313](https://www.github.com/musescore/MuseScore/issues/22313)
Resolves: [musescore#22712](https://www.github.com/musescore/MuseScore/issues/22712)
> Fix GH#22313: Set correct stem direction on pasting notes on a drum staff

- libmscore/trill.cpp
Backport of #22852
Resolves: [musescore#20856](https://www.github.com/musescore/MuseScore/issues/20856)
> Fix GH#20856: Fix ignored color on trill after opening score

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testBarlineSpan.xml
- mtest/musicxml/io/testDivsDefinedTooLate2.xml
- mtest/musicxml/io/testDivsDefinedTooLate2_ref.xml
- mtest/musicxml/io/testSystemBrackets1.xml
- mtest/musicxml/io/testSystemBrackets2.xml
- mtest/musicxml/io/testSystemBrackets3.xml
- mtest/musicxml/io/testSystemBrackets3_ref.mscx
- mtest/musicxml/io/testSystemBrackets4.xml
- mtest/musicxml/io/testSystemBrackets5.xml
- mtest/musicxml/io/testSystemDirection.xml
- mtest/musicxml/io/testSystemDividers.xml
- mtest/musicxml/io/tst_mxml_io.cpp
Backports of #22858 and #20952
Resolves: [musescore#20699](https://www.github.com/musescore/MuseScore/issues/20699)
as the commit causing the issue is also part of Mu3, this fix should be needed here too. Mu3 so far only imports "group-barline", but doesn't export it too, an addition from #20952's commit 1, 3 and 4, where in my earlier attempts to backport I couldn't get the part that exports the bracket color (commit 2 and 5) to work, so now I'm porting that without the core of the 2nd commit (exporting the coloring of brackets), No big loss, as Mu3 doesn't support coloring brackets in the first place...
> Fix: GH#20699: Fix barline spans on xml import

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testInvisibleDirection.xml
- mtest/musicxml/io/testSound1.xml
- mtest/musicxml/io/testSound2_ref.xml
- mtest/musicxml/io/testTempoOverlap_ref.xml
- mtest/musicxml/io/tst_mxml_io.cpp
> Read 'print-object' for directions and write for tempo

- libmscore/harmony.cpp
Revert "Fix #344: Modifying an element makes a chord symbol move" This reverts commit e86e962e0866aadd1e6efaa2c66e06a9ffea2f14.
Resolves: #489
> Fix GH#489: Bad y-spacing of chord symbols

- mscore/file.cpp
This reverts a(n optional and non-vital) part of #475, by reinstating an obsolete Qt function
Resolves: #491
> Fix GH#491: The export to PDF is not correct when using custom page sizes

- libmscore/tempotext.cpp
- libmscore/tempotext.h
- mscore/textpalette.cpp
Backport of #23192
Seems to crash only when using Qt6, and even there only in Debug builds, but the code is wrong even before: implicitly converting `id` to a `QChar` regardless that this is just a 16 bit value, while  ìd` is a 32 bit one.
Plus some rather unrelated includes cleanup...
> Fix (potential) crash when opening special characters dialog

- libmscore/scorefile.cpp
with an 'invalid' mscVersion (integer number rather than decimal fraction)
Resolves: https://musescore.org/en/node/357459
> Fix crash on opening a foreign generated score

- libmscore/rendermidi.cpp
"Backport" of #21925 (actually this one here existed first)
Resolves https://musescore.org/en/node/361768
This images shows that 2 ticks offset before my change:
> Make sure the MIDI pedal events start at the same tick as their starting note

- importexport/musicxml/importmxmlpass1.cpp
- mtest/musicxml/io/testTitleSwapMu.xml
- mtest/musicxml/io/testTitleSwapMu_ref.mscx
- mtest/musicxml/io/testTitleSwapSib.xml
- mtest/musicxml/io/testTitleSwapSib_ref.mscx
- mtest/musicxml/io/tst_mxml_io.cpp
Backport of #23394
Resolves: [musescore##22467](https://www.github.com/musescore/MuseScore/issues/22467)
> Fix GH#22467: Only apply credit swap to Sibelius scores on XML import

- importexport/musicxml/importmxmlpass2.cpp
Actually it should be `!m_wordsText.empty() && !rawWordsText.empty()`, but `!rawWordsText.empty()` implies `!m_wordsText.empty()`, so checking only `!rawWordsText.empty()` suffices.
Bacport of #23339, commit 1
> Check whether string is empty before calling .back()

- importexport/capella/capella.cpp
- importexport/capella/capella.h
Resolves: [musescore#23652](https://www.github.com/musescore/MuseScore/issues/23652)
'Backport' of #23654 (actually this one here existed first)
Backport of #23696
> Fix GH#23652: Possible buffer overflow in `Capella::readString()`

- libmscore/read114.cpp
- libmscore/read206.cpp
- mtest/libmscore/compat114/clefs-ref.mscx
- mtest/libmscore/compat114/fingering-ref.mscx
- mtest/libmscore/compat114/hairpin-ref.mscx
- mtest/libmscore/compat114/hor_frame_and_mmrest-ref.mscx
- mtest/libmscore/compat114/keysig-ref.mscx
- mtest/libmscore/compat114/notes-ref.mscx
- mtest/libmscore/compat114/text_scaling-ref.mscx
- mtest/libmscore/compat114/textstyles-ref.mscx
- mtest/libmscore/compat114/title-ref.mscx
- mtest/libmscore/compat114/tuplets-ref.mscx
- mtest/libmscore/compat114/tuplets_1-ref.mscx
- mtest/libmscore/compat114/tuplets_2-ref.mscx
- mtest/libmscore/compat206/frame_text2-ref.mscx
here esp. the vertical and horizontal frames and their margins, by syncing read114.cpp's `readBox()` with what read206.cpp's `readBox()` does.
Examples, Mu3 (and Mu4):
Mu1 (and Mu2 and with this PR):
Importing Mu1 and Mu2 scores marked BOTTOM_GAP of a vertical frame to not be the default setting even if it was, so I fixed that too, in the passing
Highly annoying to have to reset these 5 setting to default on every single score, I really should have done this PR back in 2019 when I switched to Mu3 and migrated loads of my old M1 and Mu2 scores. All done now, so too late for me ... (except for some 400 scores on the back burner, awaiting a properly working album feature)
'Backport' of #23648 (actually this one here existed first)
> Improve Mu1 import

- libmscore/property.cpp
Backport of #23756
Resolves: [musescore#23751](https://www.github.com/musescore/MuseScore/issues/23751)
> Fix GH#23751: Tag Pid::VOICE as always-sync property

- importexport/musicxml/exportxml.cpp
> Consistently use odd/even lyrics font style as appropriate on MusicMXL export

- libmscore/line.cpp
Backport of #23928
May not be needed in Mu3, but shouldn't harm either
> Fix another anchor crash

- libmscore/cmd.cpp
- libmscore/input.cpp
Backport of #23911
Resolves: [musescore#17931](https://www.github.com/musescore/MuseScore/issues/17931) & [musescore#21355](https://www.github.com/musescore/MuseScore/issues/21355)
> Don't skip gap rests when entering notes (GH#17931 & GH#21355)

- mtest/guitarpro/UncompletedMeasure.gpx-ref.mscx
- mtest/guitarpro/artificial-harmonic.gpx-ref.mscx
- mtest/guitarpro/dotted-gliss.gpx-ref.mscx
- mtest/guitarpro/free-time.gpx-ref.mscx
- mtest/guitarpro/keysig.gpx-ref.mscx
- mtest/guitarpro/let-ring.gpx-ref.mscx
- mtest/guitarpro/ottava2.gpx-ref.mscx
- mtest/guitarpro/ottava3.gpx-ref.mscx
- mtest/guitarpro/ottava4.gpx-ref.mscx
- mtest/guitarpro/ottava5.gpx-ref.mscx
- mtest/guitarpro/palm-mute.gpx-ref.mscx
- mtest/guitarpro/repeated-bars.gpx-ref.mscx
- mtest/guitarpro/rest-centered.gpx-ref.mscx
- mtest/guitarpro/testIrrTuplet.gpx-ref.mscx
- mtest/guitarpro/text.gpx-ref.mscx
- mtest/guitarpro/trill.gpx-ref.mscx
- mtest/guitarpro/vibrato.gpx-ref.mscx
- share/instruments/instruments.xml
> Fix GH#552: Electric Guitar (treble clef) incorrectly transposes when linking to a TAB staff

- libmscore/measure.cpp
Backport of #23907
Resolves: [musescore#20311](https://www.github.com/musescore/MuseScore/issues/20311)
> Fix local time signature spacing bug

- importexport/musicxml/importmxmlpass2.cpp
Resolves (hopefully): #554
I tested one of the XML files in the issue. Checked debug output, a bunch of:
```
/importmxmllogger.cpp:Ms::log: Error at line 169 col 10: Non-started tie terminated. No-op.
importmxmllogger.cpp:Ms::log: Error at line 185 col 10: Non-started tie terminated. No-op.
importmxmlpass2.cpp:Ms::convertNotehead: unknown notehead square
importmxmlpass2.cpp:Ms::convertNotehead: unknown notehead square
```
But that doesn't seem the main culprit. Crash on application of a fermata. Notice that the present code assumes a valid chord segment, which probably should be valid, but I think that's where it was crashing. Could be a sign of something worse (why not valid?), but by demanding validity before iterating through annotations or whatever, it should fix the issue.
Needs …
> Fix #554 - Import XML - Verify segment to prevent potential crash

- mscore/svggenerator.cpp
Backport of #24029
Resolves: [musescore#22531](https://www.github.com/musescore/MuseScore/issues/22531)
> SVG Export: Write width and height in mm, not px

- mscore/editstyle.cpp
- mscore/editstyle.ui
'Backport' of #23246 (actually this here existed first)
Resolves: [musescore#23241](https://www.github.com/musescore/MuseScore/issues/23241)
> Fix GH#23241: Header/footer special symbols tooltip closes too quickly

- libmscore/chord.cpp
- libmscore/chord.h
- libmscore/chordrest.cpp
- libmscore/navigate.cpp
- libmscore/segment.cpp
- libmscore/tuplet.cpp
- libmscore/tuplet.h
Backport of #23082
Resolves: [musescore#17600](https://www.github.com/musescore/MuseScore/issues/17600)
> Fix GH#17600: Select tuplet when calling next-element prev-element actions

- libmscore/tempotext.cpp
Resolves: [musescore#24596](https://www.github.com/musescore/MuseScore/issues/24596)
> Fix GH#24596: Follow written tempo when 'c.' added to tempo text

- importexport/musicxml/importmxmlpass2.cpp
Backport of #24915
Resolves: [musescore#24865](https://www.github.com/musescore/MuseScore/issues/24865)
> Fix Cubase XML chord symbol import

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlnotepitch.cpp
- importexport/musicxml/importmxmlnotepitch.h
- importexport/musicxml/importmxmlpass2.cpp
Resolves: [musescore#23063](https://www.github.com/musescore/MuseScore/issues/23063), the import part (export is in 3.7 since May 2022)
> Fix GH#23063: (import) MusicXML alter element not exported 

- mscore/shortcutcapturedialog.cpp
- mscore/shortcutcapturedialog.h
Backport of #24958
Resolves: [musescore#24864](https://wwwgithub.com/musescore/MuseScore/issues/24864)
> Add more keys where Shift should not be removed

- importexport/musicxml/importmxmlpass1.cpp
Backport of #24555 and (a part of) #22056, the latter having caused a bug fixed by the former, but the former leads to easier code.
Resolves: [musescore#24553](https://www.github.com/musescore/MuseScore/issues/24553)
> Fix GH#24553: MusicXML: A title like "Jazz Piece No. 5" get interpreted as a subtitle

- importexport/musicxml/importmxmlpass2.cpp
- importexport/musicxml/importmxmlpass2.h
- mtest/musicxml/io/testCueNotes3_ref.mscx
- mtest/musicxml/io/testElision_ref.mscx
- mtest/musicxml/io/testInferredCredits1_ref.mscx
- mtest/musicxml/io/testInferredCredits2_ref.mscx
- mtest/musicxml/io/testLyricBracket_ref.mscx
- mtest/musicxml/io/testLyricPos_ref.mscx
- mtest/musicxml/io/testPartNames_ref.mscx
- mtest/musicxml/io/testPlacementDefaults_ref.mscx
- mtest/musicxml/io/testPlacementOffsetDefaults.xml
- mtest/musicxml/io/testPlacementOffsetDefaults_ref.mscx
- mtest/musicxml/io/testSecondVoiceMelismata_ref.mscx
- mtest/musicxml/io/testTextOrder_ref.mscx
- mtest/musicxml/io/tst_mxml_io.cpp
* Backport of #25014 plus 2 more small changes
Resolves: [musescore#24551](https://www.github.com/musescore/MuseScore/issues/24551)
* Backport of https://github.com/musescore/MuseScore/pull/22740
Resolvers [musescore#22739](https://www.github.com/musescore/MuseScore/issues/22739)
> Reset offset when placement is changed and Discard relative-y for lyric placement 

- importexport/musicxml/exportxml.cpp
- mtest/musicxml/io/testChangeTranspose-no-diatonic_ref.xml
- mtest/musicxml/io/testChangeTranspose.xml
- mtest/musicxml/io/testInstrumentChangeMIDIportExport_ref.xml
- mtest/musicxml/io/testMultiInstrumentPart1.xml
- mtest/musicxml/io/testMultiInstrumentPart2.xml
- mtest/musicxml/io/testMultiInstrumentPart3_ref.xml
- mtest/musicxml/io/tst_mxml_io.cpp
Backport of #24932
Resolves: [musescore#17397](https://www.github.com/musescore/MuseScore/issues/17397)
> Fix GH#17397: Fully export instrument changes to MusicXML

- libmscore/keysig.cpp
Backport of #24522
Resolves: [musescore#24026](https://www.github.com/musescore/MuseScore/issues/24026) which actually isn't an issue with 3.x at all. But the change doesn't seem to harm either
> Fix GH#24026: Ensure correct key signature accidentals after clef change

- mscore/timedialog.cpp
- mscore/timedialog.h
- mscore/timedialog.ui
Backport of #25564 plus fixing clazy warnings
Resolves: [musescoe#12970](https://www.github.com/musescore/MuseScore/issues/12970)
> Fix GH#12970: Crash due to too big custom Time Signature

- libmscore/read114.cpp
- libmscore/read206.cpp
- libmscore/spanner.cpp
- libmscore/volta.cpp
- libmscore/volta.h
Backport of #25031
Also fix most clazy warnings
Resolves: [musescore#25031](https://www.github.com/musescore/MuseScore/issues/25031), which may not be a Mu3 issue at all, but doesn't seem to harm either
> Enforce volta anchor on all scores

- importexport/musicxml/exportxml.cpp
Backport of #25594
Resolves: [musescore#23499](https://wwwgithub.com/musescore/MuseScore/issues/23499)
> Fix GH#23499: Remove extra treatment for tab pitch in MusicXML export

- libmscore/line.cpp
- mtest/libmscore/spanners/linecolor01-ref.mscx
Backport of #25789
Resolves: [musescore#25783](https://wwwgithub.com/musescore/MuseScore/issues/25783)
> Fix GH#25783: Write color only once for line spanners

- CMakeLists.txt
- Makefile
- vtest/gen
by disabling WebEngine support.
It now uses the system's default browser instead.
Also resolves the issue with a blank dialog when using Save online, like seen with the Windows 32-bit builds as well as with the 3.6.2 Windows versions. 
No idea how the Mac and Linux version behave, feedback wanted...
Resolves: #261 (and #716)
> Fix GH#261: Interfacing with musescore.com crashes program

- libmscore/edit.cpp
Resolves: #724
See https://musescore.org/en/node/372754 and https://github.com/Jojo-Schmitz/MuseScore/pull/328#issuecomment-2543031308
> Fix crash when deleting last voice 2 rest in note input mode

- mscore/musescore.cpp
- mscore/shortcut.cpp
This reverts changes to musescore.cpp, line 8255 and 8256, part of commit https://github.com/Jojo-Schmitz/MuseScore/commit/ba6d337c6066ae8aa37c46bcd9968dce13fa0dcd
It adds some other fixes.
Resolves: #679
> Fix GH#679: Clicking on MSCZ file fails to open if Mu3.7 is already running

- libmscore/sym.cpp
- mscore/musescore.qrc
- mscore/musescorefonts-Mac.qrc
> Fix GH#698: Mac build doesn't start due to missing fonts

- build/ci/macos/setup.sh
Resolves: [musescore#16533](https://www.github.com/musescore/MuseScore/issues/16533)
Resolves: [musescore#17740](https://www.github.com/musescore/MuseScore/issues/17740)
Backport of #17772, needed as this branch also used Qt 5.15 and not 5.9 like 3.6.2 and earlier
Needs QWebEngine though, that so far isn't part of https://s3.amazonaws.com/utils.musescore.org/Qt5159_mac.zip
Edit: we no longer use/need that.
> Use newer Qt version (5.15.9) on macOS

- mscore/file.cpp
- mscore/plugin/api/qmlpluginapi.cpp
Resolves: https://musescore.org/en/node/369130
> Allow reading of corrupt or 'wrong' version scores in plugins without asking confirmation

- build/ci/macos/notarize.sh
> macOS notarization: add automatic retry

- libmscore/edit.cpp
> Remove some redundant code from `cmdAddTimeSig`

- build/ci/macos/setup.sh
and GH# 227: MacOS - playback is greyed out because can't find audio device
by partly reverting 7f89edd, just with a) a newer version of the MacPorts and b) the Ventura (13) variant, being the one GitHub CI builds 3.7 on currently
Resolves: https://musescore.org/en/node/320037
Resolves: #227
> Fix #320037: PortAudio Grayed out in Musescore 3.6.2, but working on 3.5.0

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- libmscore/figuredbass.cpp
- libmscore/figuredbass.h
- libmscore/fret.cpp
- libmscore/fret.h
Backport of #25912
Resolves: [musescore#25891](https://www.github.com/musescore/MuseScore/issues/25891)
And a (partial) backport of d2285d8a to move MusicXML export of fretboard diagrams from fret.cpp and figured bass from figuredbass.cpp to exportxml.cpp and the import of figured bass from figuredbass.cpp to importmxmlpass2.cpp
Also doing a remainder from backporting #19132
> Fix GH#25891: do not write muted strings

- importexport/musicxml/exportxml.cpp
- libmscore/system.cpp
- libmscore/system.h
Backport of https://github.com/musescore/MuseScore/pull/25960
Resolves: [musescore#22098](https://www.github.com/musescore/MuseScore/issues/22098)
> Fix GH#22098: staff distance with hidden staves

- libmscore/cmd.cpp
- libmscore/measure.cpp
Backport of #21975
Mu3 didn't crash in that particular scenario (but does when there's no note in the measure with the chord symbol, hence the 2nd commit), but now does render the realized chord symbols differently and better, before:
after (when realizing chord symbols via right-click on the C):
Resolves: [musescore#21672](https://www.github.com/musescore/MuseScore/issues/21672)
> Fix GH#21672: Prevent crash when realizing chords over multi-measure rests

- importexport/musicxml/importmxmlpass2.cpp
- libmscore/hairpin.cpp
- mtest/musicxml/io/testInferredCrescLines2_ref.mscx
- mtest/musicxml/io/testInferredCrescLines_ref.mscx
- mtest/musicxml/io/testInferredDynamicsExpression_ref.mscx
- mtest/musicxml/io/testInferredDynamics_ref.mscx
Backport of #23125
Resolves: [musescore#23119](https://www.github.com/musescore/MuseScore/issues/23119)
> Fix GH#23119: Ensure TextLineBase properties are written for hairpins

- libmscore/measurebase.cpp
- libmscore/repeat.cpp
- libmscore/repeatlist.cpp
Resolves: https://musescore.org/en/node/368929
Resolves: [musescore#24802](https://www.github.com/musescore/MuseScore/issues/24802)
Not exactly sure what the deal is here, but the crash does happen while processing voltas, and the score does have them for both visible staves, and is also having some invisible staves (without voltas).
Just making the invisible staves visible fixes the crash, just removing the 'superfluous' voltas does not.
> Fix #368929: Crash on playback with hidden staves and 'superfluous' voltas

- share/locale/mscore_pl.ts
Update Polish translation
Sorry, but I see that I used the quotes in these cases.
Resolves: *(direct link to the issue)*
*(short description of the changes and the motivation to make the changes)*
> Update Polish translation

- libmscore/property.cpp
Backport of #26279, commit 2 (commit 1 doesn't seem to apply to Mu3)
Resolves: [musescore#25356](https://www.github.com/musescore/MuseScore/issues/25356)
> Fix system text line sync issues

- libmscore/measure.cpp
- libmscore/measure.h
- mscore/dragdrop.cpp
Backport of #26289 and fix clazy warnings
Resolves: [musescore#25145](https://www.github.com/musescore/MuseScore/issues/25145)
> Fix GH#25145: Crash relating to StaffTypeChange

- libmscore/select.cpp
Backport of #20634 and #25467, plus fixing some clazy warnings
Resolves: [musescore#15321](https://www.github.com/musescore/MuseScore/issues/15321)
> Fix GH#15321: Allow Removal of Spanners from Range Selections

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/testColors.xml
'Backport' of #26495 (this here existed first, at least the part about beams)
Resolves: [musescore#26494](https://www.github.com/musescore/MuseScore/issues/26494)
Current restriction: doesn't work for grace note beams
Further restriction: if in the MusicXML different colors are set for different strokes of a beam, like for 16ths' beams' upper and lower stroke, the last color wins, MuseScore does not allow for this, it colors the entire beam, not single strokes of it.
> Fix GH#26494: MusicXML Import - Beams don't have their color imported

- .github/workflows/build_macos.yml
- build/ci/macos/build.sh
- build/ci/macos/package.sh
- build/ci/macos/setup.sh
by separating Mac builds for Intel and Apple silicone and using HomeBrew for one and MacPorts for the other. They still remain universal builds, not native ones though, so should both run on either CPU type (but may crash on one and have no sound on the other).
Also being more explicit, for the MacPorts, which packages to use and in what order, rather than relying on automatic dependencies.
Disabling BUILD_UI_MU4, which doesn't apply to Mu3 at all.
And while at it, enabling building PortableApps for Windows in PRs too, not just in nightly builds, esp. as it doesn't seem to cause any delay in the builds.
Resolves: #775
> Fix GH#775: Crash due to missing/bad libvorbisfile.3.dynlib

- mscore/scoreview.cpp
Backport of #18951 (closed meanwhile, maybe by accident) plus fixing some a clazy warnings
Resolves: [musescore#16644](https://www.github.com/musescore/MuseScore/issues/16644)
> Repeat last chord after inputting a rest

- libmscore/fret.cpp
- libmscore/fret.h
- libmscore/harmony.cpp
- libmscore/rendermidi.cpp
Backport of #26703 plus fixing clazy warnings
Resolves: [musescore#26523](https://www.github.com/musescore/MuseScore/issues/26523)
> Fix GH#26523: Crash on deleting instrument if last staff contains fretboard diagra

- importexport/musicxml/importmxmlpass2.cpp
Backport of #25629
Resolves: [musescore#25617](https://www.github.com/musescore/MuseScore/issues/25617)
> Fix GH#25617: Prevent crash importing MusicXML file containing grace rest followed by tuple starting with rest

- importexport/musicxml/importmxmlpass2.cpp
Backport of #24709, the only relevant part for Mu3, a memory leak and an incorrect logic for logging an error, both in importmxmlpass2.cpp
> Fix GH#24704: ensure xml parse can cope with comments after empty notes

- .github/workflows/build_all.yml
- .github/workflows/build_linux.yml
- .github/workflows/check_visual_tests.yml
- .github/workflows/translate_tx_pull_to_s3.yml
- .github/workflows/update_release_info.yml
- build/ci/linux/setup.sh
as 20.04 will get deprecated on GitHub CI on April 1st, see https://github.com/actions/runner-images/issues/11101
> Update Linux builds to use Ubuntu 22.04

- audio/exports/exportmidi.cpp
- audio/midi/event.h
- audio/midi/midifile.cpp
- miditools/midifile.cpp
Replace new unsigned char allocations with std::vector<unsigned char> and make sure that MidiEvent::setEData takes vector reference rather than raw pointer.
Backport of #26798
Resolves: [musescore#26414](https://www.github.com/musescore/MuseScore/issues/26414)
> Fix GH#26414: Memory leak in MIDI export

- importexport/musicxml/importmxmlpass2.cpp
- mtest/musicxml/io/importTie5.xml
- mtest/musicxml/io/tst_mxml_io.cpp
Backport of #26467
Resolves: [musescore#26453](https://www.github.com/musescore/MuseScore/issues/26453)
> Fix GH#26453: Change tie import exclusion

- importexport/musicxml/exportxml.cpp
Backport of #26190
Resolves: [musescore#17398](https://www.github.com/musescore/MuseScore/issues/17398)
> Fix GH#17398: Mark hidden staves in MusicXML export

- libmscore/note.cpp
Backport of #27037
Resolves: [musescore#26997](https://www.github.com/musescore/MuseScore/issues/26997)
> Fix GH#26997: Limit edit leading space by drag

- mscore/pagesettings.cpp
by making the step width for the scaling value smaller.
Partly resolves: #331 (by provideing better (i.e. smaller) defaults)
See also #27373, which does the same for upstream master
---
Resolves #331 (finally!)
See https://musescore.org/en/node/376837#comment-1286408
> Fix GH#331: Awkward single-digit entry required in Page Setup field

- importexport/musicxml/exportxml.cpp
This PR adds export of frames on dynamics to the MusicXML support.
Backport of #27289
> [MusicXML] export of frames on dynamics, accidental size, and fretboard diagram colors

- libmscore/edit.cpp
Backport of #27485
Resolves: [musescore#27277](https://www.github.com/musescore/MuseScore/issues/27277) (unlikely an issue with 3.x)
> Fix big time sig appear in part

- libmscore/read114.cpp
- libmscore/read206.h
- mtest/libmscore/compat114/accidentals-ref.mscx
- mtest/libmscore/compat114/articulations-ref.mscx
- mtest/libmscore/compat114/chord_symbol-ref.mscx
- mtest/libmscore/compat114/clef_missing_first-ref.mscx
- mtest/libmscore/compat114/clefs-ref.mscx
- mtest/libmscore/compat114/drumset-ref.mscx
- mtest/libmscore/compat114/fingering-ref.mscx
- mtest/libmscore/compat114/hairpin-ref.mscx
- mtest/libmscore/compat114/hor_frame_and_mmrest-ref.mscx
- mtest/libmscore/compat114/keysig-ref.mscx
- mtest/libmscore/compat114/markers-ref.mscx
- mtest/libmscore/compat114/noteheads-ref.mscx
- mtest/libmscore/compat114/notes-ref.mscx
- mtest/libmscore/compat114/notes_useroffset-ref.mscx
- mtest/libmscore/compat114/ottava-ref.mscx
- mtest/libmscore/compat114/pedal-ref.mscx
- mtest/libmscore/compat114/slurs-ref.mscx
- mtest/libmscore/compat114/style-ref.mscx
- mtest/libmscore/compat114/style.mscx
- mtest/libmscore/compat114/tamtam-ref.mscx
- mtest/libmscore/compat114/text_scaling-ref.mscx
- mtest/libmscore/compat114/textline-ref.mscx
- mtest/libmscore/compat114/textstyles-ref.mscx
- mtest/libmscore/compat114/title-ref.mscx
- mtest/libmscore/compat114/tremolo2notes-ref.mscx
- mtest/libmscore/compat114/tuplets-ref.mscx
- mtest/libmscore/compat114/tuplets_1-ref.mscx
- mtest/libmscore/compat114/tuplets_2-ref.mscx
Including page number offset
This fixes a regression vs. MuseScore 2.x
Resolves: [musescore#27546](https://github.com/musescore/MuseScore/issues/27546)
'Backport' of #27464 (actually this PR here existed first)
> Import page format settings from MuseScore 1.x scores 

- libmscore/tremolobar.cpp
- mscore/chordview.cpp
- mscore/drumview.cpp
- mscore/pianoroll/pianoview.cpp
Backport of #27184
Resolves: [musescore#17838](https://www.github.com/musescore/MuseScore/issues/17838)
> Fix GH#17838: Persist general properties of a TremoloBar

- global/settings/types/preferencekeys.h
- importexport/musicxml/exportxml.cpp
- mscore/preferences.cpp
Backport of #27764 (and a formerly omitted part of #20370's 3rd commit)
Resolves: [musescore#27763](https://www.github.com/musescore/MuseScore/issues/27763)
> Fix MusicXML incompatibility with MuseScore 3.6.2 (and older)

- audio/exports/exportmidi.cpp
- global/settings/types/preferencekeys.h
- importexport/midiimport/importmidi_lyrics.cpp
- mscore/preferences.cpp
- mscore/prefsdialog.cpp
- mtest/importmidi/lyrics_time_0.mscx
- mtest/importmidi/lyrics_voice_1.mscx
Backport of #27500/#27730, with an advanced preference to (un)set this
> Append space to lyrics when exporting MIDI (and remove on import)

- libmscore/accidental.cpp
- libmscore/accidental.h
Backport of #27450 plus, following a clazy warning, improving the struct's padding, saving 8 bytes per entry, 1176 bytes in total
> Fix cent offset for AEU accidentals

- libmscore/read114.cpp
Resolves: [musescore#27832](https://www.github.com/musescore/MuseScore/issues/27832)
'Backport'  of #27839 (actually this here existed first)
> Fix import of 1.x jumps (and markers)

- libmscore/note.cpp
Fix playback bug only in #523 and #762
Redundant resets in mouse move event
> Fix #523 and #762

- libmscore/note.cpp
- libmscore/staff.h
Backport of #27996
Resolves: [musescore#20398](https://github.com/musescore/MuseScore/issues/20398)
> Fix issue unable to drag string on tablature under ottava

- libmscore/barline.cpp
Backport of #26686
Resolves: [musescore#26675](https://www.github.com/musescore/MuseScore/issues/26675)
> Fix GH#26675: Correct barline on oneline to hidden staff

- mscore/scoreview.cpp
There's more combinations that didn't work though, basically any full measure rest in any time signature
Resolves: #971
> Fix GH#971: Can't create 6-lets on measures rests in 9/8

- mscore/plugin/api/elements.h
Backport of #28386
Resolves: [musescore#28385](https://www.github.com/musescore/MuseScore/issues/28385)
> Fix GH#28385: Allow plugin elements to call subtype

- build/MacOSXBundleInfo.plist.in
Backport of #28767
Resolves: [musescore#28744](https://wwwgithub.com/musescore/MuseScore/issues/28744)
> Add .midi extension support to macOS Info.plist

- build/ci/linux/package.sh
- build/ci/linux/tools/make_appimage.sh
Resolves: #987
by a) bringing make_upimage.sh closer to upstream/master's
and b) disabling `UPDATE_INFORMATION` for "stable" and "nigthly" builds, as it doesn't work at all but also the mechanism behind it doesn't apply to my fork (like not uploading artifacts to OSUOSL).
I don't quite understand though why this seems to have worked or at least didn't cause build failures up to some 3 weeks ago.
> Fix GH#987: CI nightly build failures for Linux

- importexport/musicxml/exportxml.cpp
export all remaining articulations as `other-articulation`
Backport of #27314
> [MusicXML] export all articulations

- libmscore/layout.cpp
Backport of #29935
Resolves: {musescore#29695](https://www.github.com/musescore/MuseScore/issues/29695)
> Fic GH#29695: Change stacking order for system text

- importexport/musicxml/exportxml.cpp
- importexport/musicxml/importmxmlpass2.cpp
- libmscore/realizedharmony.cpp
Adds import for `eyeglasses` element and extends import and export for special coda and segno glyphs.
Backport of #298923
> [MusicXML] minor improvements for symbols
